config/routes.rb
Rails.application.routes.draw do
    get 'main' => 'time_records#today'
    root 'time_records#index'

    post 'time_records/batch_create'

    resources :time_records

end

app/models/time_record.rb
class TimeRecord < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/time_records_controller.rb
class TimeRecordsController < ApplicationController
  before_action :set_time_record, only: [:show, :edit, :update, :destroy]

  # GET /time_records
  # GET /time_records.json
  def index
      day = params[:day]
      if day
         @day = params[:day].to_date
      else 
         @day = Date.today
      end
      @time_records_hash = time_records_hash_for_day(@day)
      respond_to do | format |
          format.html 
          format.js
      end
  end

  # GET /time_records/1
  # GET /time_records/1.json
  def show
  end


  #def today
      #@time_records_hash = time_records_hash_for_day(Date.today)
  #end


  def get_record(day, hour, quarter)
    TimeRecord.where(day: day, hour: hour, quarter: quarter)
  end

  # GET /time_records/new
  def new
    @time_record = TimeRecord.new
  end

  # GET /time_records/1/edit
  def edit
  end

  # POST /time_records
  # POST /time_records.json
  def create
    @time_record = TimeRecord.new(time_record_params) 

    respond_to do |format|
      if @time_record.save
        format.html { redirect_to @time_record, notice: 'Time record was successfully created.' }
        format.json { render :show, status: :created, location: @time_record }
        format.js
      else
        format.html { render :new }
        format.json { render json: @time_record.errors, status: :unprocessable_entity }
      end
    end
  end

  def batch_create
      @day = params[:day]
      for hour in 6..23
          for quarter in 1..4
              key = "#{hour}-#{quarter}"
              event = params[key]
              if event && event.strip.length>0
                  record = find_record({day: @day, hour: hour, quarter: quarter})
                  if record
                      if record.event != event
                          record.event = event
                          record.save
                      end
                  else 
                      TimeRecord.create({day: @day, hour: hour, quarter: quarter, event: event}) 
                  end
              end
          end
      end

      @time_records_hash = time_records_hash_for_day(@day)
      render 'index'
      #time_records_hash_for_day(day)
      #respond_to do |format|
          #format.html{render 'today'}
          #format.js
      #end
  end

  # PATCH/PUT /time_records/1
  # PATCH/PUT /time_records/1.json
  def update
    respond_to do |format|
      if @time_record.update(time_record_params)
        format.html { redirect_to @time_record, notice: 'Time record was successfully updated.' }
        format.json { render :show, status: :ok, location: @time_record }
      else
        format.html { render :edit }
        format.json { render json: @time_record.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /time_records/1
  # DELETE /time_records/1.json
  def destroy
    @time_record.destroy
    respond_to do |format|
      format.html { redirect_to time_records_url, notice: 'Time record was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_time_record
      @time_record = TimeRecord.find(params[:id])
    end

    def time_records_hash_for_day(day)
        time_records = TimeRecord.where(day: day)
        time_records_hash = {}
        time_records.each do |record|
            time_records_hash[record.hour.to_s+"-"+record.quarter.to_s] = record.event
        end
        return time_records_hash
    end
    # Never trust parameters from the scary internet, only allow the white list through.
    def time_record_params
      params.require(:time_record).permit(:day, :hour, :quarter, :event, :note)
    end

    def find_record(time_params)
        TimeRecord.where(time_params).first
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/time_records_helper.rb
module TimeRecordsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Newton</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <link rel="stylesheet" href="http://yui.yahooapis.com/pure/0.5.0/pure-min.css">
</head>
<body>

<div id="container">
    <%= yield %>
</div>

</body>
</html>

app/views/time_records/_form.html.erb
<%= form_for(@time_record) do |f| %>
  <% if @time_record.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@time_record.errors.count, "error") %> prohibited this time_record from being saved:</h2>

      <ul>
      <% @time_record.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :day %><br>
    <%= f.date_select :day %>
  </div>
  <div class="field">
    <%= f.label :hour %><br>
    <%= f.number_field :hour %>
  </div>
  <div class="field">
    <%= f.label :quarter %><br>
    <%= f.number_field :quarter %>
  </div>
  <div class="field">
    <%= f.label :event %><br>
    <%= f.text_field :event %>
  </div>
  <div class="field">
    <%= f.label :note %><br>
    <%= f.text_area :note %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/time_records/create.js.erb
$("#msg").text("<%= @time_record.event %>"+" created")

app/views/time_records/edit.html.erb
<h1>Editing time_record</h1>

<%= render 'form' %>

<%= link_to 'Show', @time_record %> |
<%= link_to 'Back', time_records_path %>

app/views/time_records/index.html.erb
<div id="msg"></div>

<%= form_tag '/time_records/batch_create', class: 'pure-form' do %>
    <div class="div_select_day">
        <%= text_field_tag 'day', @day %><br/>
    </div>
    <table>
    <% for hour in 6..23 %>
        <tr>
            <td class="hour">
                <%= hour %>
            </td>
            <td>
                <% for quarter in 1..4 %>
                    <% key = hour.to_s+"-"+quarter.to_s %>
                    <%= text_field_tag key, @time_records_hash[key] , class: 'record_textfield' %>
                <% end%>
            </td>
        </tr>
    <% end %>
    </table>
    <div class="div_submit">
        <%= submit_tag 'Submit', class: "pure-button pure-button-primary" %>
    </div>
<% end %>

app/views/time_records/index.js.erb
<% for hour in (6..23) do %>
    <% for quarter in 1..4 %>
        <% key = "#{hour}-#{quarter}"  %>
        $("#<%= key %>").val("<%= @time_records_hash[key] %>")
    <% end %>
<% end %>

app/views/time_records/new.html.erb
<h1>New time_record</h1>

<%= render 'form' %>

<%= link_to 'Back', time_records_path %>

app/views/time_records/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Day:</strong>
  <%= @time_record.day %>
</p>

<p>
  <strong>Hour:</strong>
  <%= @time_record.hour %>
</p>

<p>
  <strong>Quarter:</strong>
  <%= @time_record.quarter %>
</p>

<p>
  <strong>Event:</strong>
  <%= @time_record.event %>
</p>

<p>
  <strong>Note:</strong>
  <%= @time_record.note %>
</p>

<%= link_to 'Edit', edit_time_record_path(@time_record) %> |
<%= link_to 'Back', time_records_path %>